---
title: "Week 3: Part 2 - Brainstorm: Technologies in Biology"
author: "Holub Martin, Samuel Gunz, Stutz Sascha, Meili Peter"
date: "10 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Goal
The goal of this document is to give a small insight into the topic of cytometry. This will be done with a three point summary as well as links to a few good resources covering the topic. While the additional objective is to get hands on experience of how group assignments can be done in GitHub.


## Cytometry

+ Measurement of charactersitics of cells (both individual and populations) including cell size, cell count, cell shape and structure, cell cycle phase, DNA content and presence of proteins.[1](https://en.wikipedia.org/wiki/Cytometry)

+ In **flow cytometry**, cells are suspendend in a liquid solution and injected into a stream of sheath fluid and henceforth additionally focused. Individual cell proberties are interrogated by optical or conductivity based measurements. Flow properties are cytometry has a frequently used extension - cell sorting, where cells are split into indivdual streams based on their properties. [2](http://isac-net.org/About/What-is-Cytometry.aspx) [3](http://www.abcam.com/protocols/introduction-to-flow-cytometry)

+ Flow cytometry often uses fluorescence tagging of cells, the application thereof is often complicated by wide emission spectra of fluorophores. This issue is adressed in **mass cytometry**, where antibody-tagged proteins in cells are chemically bondend to unique pure elements, often metals. The cells are then focsued to a stream and can be analyzed based on the mass of conjugated element, e.g. by time-of-flight mass spectrometer. [4](https://en.wikipedia.org/wiki/Time-of-flight_mass_spectrometry) [5](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4860251/)

## Resources
[1: https://en.wikipedia.org/wiki/Cytometry](https://en.wikipedia.org/wiki/Cytometry)
[2: http://isac-net.org/About/What-is-Cytometry.aspx](http://isac-net.org/About/What-is-Cytometry.aspx)
[3: http://www.abcam.com/protocols/introduction-to-flow-cytometry](http://www.abcam.com/protocols/introduction-to-flow-cytometry)
[4: https://en.wikipedia.org/wiki/Time-of-flight_mass_spectrometry](https://en.wikipedia.org/wiki/Time-of-flight_mass_spectrometry)
[5: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4860251/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4860251/)
